### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by nathanshammah** [mezze-team/mezze#1]
Since this repository is public, having a license would protect the contributors. [Here](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository) are some details. Basically adding a new file from the web interface and calling it LICENSE.md would make several templates appear, whose basic differences are highlighted in a table. 

Happy to open a PR to add it if the contributors have one in mind.

**Comment by k-m-schultz** [comment]
See [LICENSE](https://github.com/mezze-team/mezze/blob/master/LICENSE)
